version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_go_net
  
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017" 
    restart: unless-stopped 

networks:
  rabbitmq_go_net:
    driver: bridge